### ISSUE TITLE
Underscore in R chunk name produces error in figure caption

### ISSUE THREAD

**Issue by m-Py** [crsh/papaja#101]
Hello Frederik,  
I think that I found an error that can occur in papaja figure captions. It is only a minor issue, but it is not obvious how it occurs, so I thought I share this:

When I specify a chunk name that contains an underscore (e.g., "my_chunk") in an R chunk that produces a plot, the figure caption contains "(#fig:my_chunk)". [Here](https://gist.github.com/m-Py/f2f0cfdd8c5109a3d880247a1b3e47f8) is a file that reproduces this behavior. I checked whether this also occurs for normal pdf_output, but it seems to be related to papaja. 

Cheers,  
Martin

**Comment by crsh** [comment]
Hi Martin, true, this is due to the way the underlying `bookdown` package and the format `pdf_document2()` implements cross-references and from the sound of Yihui's response in [this issue](https://github.com/rstudio/bookdown/issues/157) I don't think this will change any time soon... It's a little unsatisfactory for me, too, as I habitually use underscores in my chunk names but it's something I'm learning to live with.

**Comment by crsh** [comment]
To add to my previous response, this behavior also affects table cross-references and I have documented it in the example file (p. 7, l. 78).

**Comment by m-Py** [comment]
Ah okay, sorry, I did not know that this issue was known already!

**Comment by crsh** [comment]
No, problem. My favorite issues are those that I can just close. :wink:
