### ISSUE TITLE
easy identification / deidentification of authors

### ISSUE THREAD

**Issue by mcbeem** [crsh/papaja#114]
When submitting a manuscript for publication, it is customary to prepare a version in which the authors' identifying information has been removed. 

Would it be possible to add this as a feature to _papaja_?

Perhaps as a TRUE/FALSE flag that could be set in the manuscript's preamble..?

**Comment by crsh** [comment]
Hi, yeah, I very much like that idea. What do you think would need to be removed? Of the top of my head I'd think

1. Author names and affiliation on the title page
2. Author note containing departmental affiliations
3. Identifying references

All three of these are supported by the `apa6` LaTeX class. As long as you are happy with relying on LaTeX and have no need to create a Word document with `papaja::apa_word()` 1. and 2. are easy. You can pass any class options to `apa6` via the `class` option in the YAML header:

~~~{YAML}
class: "man, mask"
~~~

This would create a manuscript-style document without author information or author note. To hide references on demand you need to use `biblatex` instead of `pandoc-citeproc`. This can be done like so:

~~~{YAML}
output:
  papaja::apa6_pdf:
    citation_package: natbib
~~~

That way you can use `\maskcite` to include hideable references. See the [`apa6` manual](http://ftp.gwdg.de/pub/ctan/macros/latex/contrib/apa6/apa6.pdf).

I believe 1. and 2. should also be easy to enable for Word documents and I'll leave this issue open as a reminder to implement this feature some time in the future. I don't think, however, there is a `pandoc-citeproc` equivalent of `\maskcite`.

**Comment by crsh** [comment]
I just pushed a commit to the development branch (`devtools::github_install("crsh/papaja", ref = "devel")`) that adds a `mask` option to the YAML front matter. In `apa6_pdf()` it activates the mask option and in `apa6_word()` it removes author names, affiliations, and author note from the title page.

**Comment by mcbeem** [comment]
That is so cool! Thanks. This is a very useful feature. 

Matt

**Comment by taktsun** [comment]
Hello, sometimes, journal editors want us to mask anything in the manuscript that can identify the team of authors. In such cases, we need to replace certain in-text info (e.g., normal OSF link to view-only OSF link; funding information etc). Is it possible to combine this mask setting with some sort of if-else statement to achieve this?
