### ISSUE TITLE
keep_md not working for apa6_word

### ISSUE THREAD

**Issue by kneijenhuijs** [crsh/papaja#115]
Trying to use the `keep_md` functionality of RMarkdown, when knitting to apa6_word does not work. When using the regular expression:
```
output            : papaja::apa6_word:
                              keep_md: true
```
A scanning error occurs. When using the non-regular expression (that usually works regardless):
```
output            : papaja::apa6_word
keep_md: true
```
The error does not occur, but the markdown file is not retained.

**Comment by crsh** [comment]
Hi, thanks for the report. To pass options to `papaja::apa6_word()` or other formats you have to slightly change the formatting of the YAML. It should work like this:

~~~{YAML}
output:
  papaja::apa6_word:
    keep_md: true
~~~

Taking a closer look, I just realized that this approach won't help you with the issue we discussed via e-mail. The title page is added in a post-processing step, apparently after the Markdown file is saved. I would need to overwrite the original output and I'm currently not sure whether that is generally a good idea. I need to think more about this.

**Comment by kneijenhuijs** [comment]
I didn't realise the newline actually mattered in this regard. Bummer that the title page is added in post-processing, but I should be able to use csl files to customize the document (almost) as far as I need it to. Thanks for looking into it!

**Comment by crsh** [comment]
You could also always steal the preprocessor function ([here](https://github.com/crsh/papaja/blob/master/R/apa6_formats.R#L79) and [here](https://github.com/crsh/papaja/blob/master/R/apa6_formats.R#L247)) and start from there.

I'll close this issue because the question regarding `keep_md` is resolved but feel free to ask further questions regarding the customization issue via e-mail.
