### ISSUE TITLE
citation after em dash

### ISSUE THREAD

**Issue by m-Py** [crsh/papaja#120]
Hello Frederik,

I found some strange behavior when using an <a href ="http://blog.apastyle.org/apastyle/2010/09/computer-editing-tip-em-dashes.html">em dash</a> in papaja. Probably this is not related to papaja, but rmarkdown, but I wanted to let you know anyway. When writing the following, the pdf renders a link (which looks like this: `methods-\/-\/-@R-papaja`) that opened my email program when I clicked on it.

```
In the introduction---and not in the methods---@R-papaja proposed to use 
em-dashes to draw a reader's attention.
```

<a href ="https://gist.github.com/m-Py/ae03960e2274a90a1216430625731d43">This gist</a> produces the result I am talking about.

Cheers, Martin

**Comment by crsh** [comment]
Hi Martin,

interesting. As you suspect, this is not a `papaja` problem. You can produce the same behavior with `rmarkdown::pdf_document()`. For PDF documents the following is a quick fix to the problem:

~~~
In the introduction---and not in the methods---\phantom{}@R-papaja proposed to use 
em-dashes to draw a reader's attention.
~~~

Interestingly, it doesn't matter if `\phantom{}` is in front or behind the em dash. In fact, it appears you can replace `\phantom{}` in either location by anything but letters or numbers and the citation is rendered as expected.

I suspect this is a `pandoc` issue because the dashes are also escaped if you render the document without `pandoc-citeproc`.

I'll close this issue as it's not related to `papaja` but feel free to keep me and others posted here.
