### ISSUE TITLE
author note on second page

### ISSUE THREAD

**Issue by ericpgreen** [crsh/papaja#150]
Great template.

I'm finding it hard to fit all of the author info on the title page. It's spilling onto the second page, but the "Author Note" heading still appears on the title page. Is there a way to force the author note onto the second page, pushing the abstract to the third page?

**Comment by crsh** [comment]
Hi Eric,

this is a peculiar behavior of the underlying `apa6` LaTeX document class, which I don't quite understand, yet. A crude fix for this problem is to add a note like the following to the YAML header:

```YAML
note: "\\clearpage"
```

This will clear the page below the affiliations and move the entire acknowledgement section to the second and the abstract to the third page.

**Comment by ericpgreen** [comment]
Very helpful, thanks!

**Comment by pmcharrison** [comment]
FYI, this solution used to work for me but it now doesn't: instead we get '\clearpage' written in plain text in the PDF.

**Comment by sdparsons** [comment]
hey @pmcharrison I've been combating this for the past hour. If you move the \clearpage into the header-includes within a note it works for me. e.g. (found in a roundabout way because someone wanted to add latex to their note for italics)

header-includes: #allows you to add in your own Latex packages
- \note{\clearpage}

**Comment by pmcharrison** [comment]
Oh hey that's great to know! Thanks for sharing @sdparsons !
