### ISSUE TITLE
Failed to compile .tex

### ISSUE THREAD

**Issue by PenelopeLQ** [crsh/papaja#151]
Hello,

First of all, thank you all for the good work! I'm new to papaja but it already seems to be a powerful package. I managed to knit my text into a docx file and everything looked fine. However, I could not produce the pdf file and it seems to be stuck at this step and gives the error message:
`sh: pdflatex: command not found`
`Error: Failed to compile Papaja_test.tex.`
`Execution halted`

I'm using R 3.4.0 and RStudio 1.0.143. I downloaded the latest MacTex and removed previous versions of LaTex as well. My system is a MacOs El Capitan, which might have caused the problem according to this: http://www.tug.org/mactex/elcapitan.html and this: https://tex.stackexchange.com/questions/271221/texmaker-command-not-found-on-macos-el-capitan . But I'm not able to solve the problem.

It may be some very simple mistake, but I would really appreciate your help here.

Thanks!

**Comment by crsh** [comment]
Hi Penelope,

this problem is really unrelated to `papaja`, but a problem between your MacTeX installation and `rmarkdown`. Try opening the terminal and entering `pdflatex -v`? If that gives information on the installed version of `pdfTeX` it would seem that RStudio is looking for `pdflatex` in the wrong place. I read somewhere that [reinstalling RStudio after upgrading MacTeX](https://support.rstudio.com/hc/en-us/articles/211833568-Fixing-missing-TeX-issue-in-OS-X-10-11-El-Capitan) can help. Otherwise try setting up a symbolic link to the correct location as detailed [here](https://stackoverflow.com/a/22487657/914024).

Good luck!
