### ISSUE TITLE
false compiling of Umlaute

### ISSUE THREAD

**Issue by peter1328** [crsh/papaja#159]
papaja does not correctly compile German Umlaute (such as inserting an "ü" in the title of the default example document), even if I save the document with utf8. When I switch the output to a regular pdf_document, it works.

**Comment by peter1328** [comment]
R Session info (Windows 10, MikTeX):

Session info ------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.0 (2017-04-21)
 system   x86_64, mingw32             
 ui       RStudio (1.1.383)           
 language (EN)                        
 collate  German_Switzerland.1252     
 tz       Europe/Berlin               
 date     2017-11-30                  

Packages ----------------------------------------------------------------------
 package    * version    date       source                      
 backports    1.1.1      2017-09-25 CRAN (R 3.4.1)              
 base       * 3.4.0      2017-04-21 local                       
 colorspace   1.3-2      2016-12-14 CRAN (R 3.4.0)              
 compiler     3.4.0      2017-04-21 local                       
 curl         3.0        2017-10-06 CRAN (R 3.4.2)              
 datasets   * 3.4.0      2017-04-21 local                       
 devtools     1.13.4     2017-11-09 CRAN (R 3.4.2)              
 digest       0.6.12     2017-01-27 CRAN (R 3.4.0)              
 evaluate     0.10.1     2017-06-24 CRAN (R 3.4.2)              
 ggplot2      2.2.1      2016-12-30 CRAN (R 3.4.0)              
 git2r        0.19.0     2017-07-19 CRAN (R 3.4.2)              
 graphics   * 3.4.0      2017-04-21 local                       
 grDevices  * 3.4.0      2017-04-21 local                       
 grid         3.4.0      2017-04-21 local                       
 gtable       0.2.0      2016-02-26 CRAN (R 3.4.0)              
 htmltools    0.3.6      2017-04-28 CRAN (R 3.4.0)              
 httr         1.3.1      2017-08-20 CRAN (R 3.4.2)              
 knitr        1.17       2017-08-10 CRAN (R 3.4.2)              
 lazyeval     0.2.1      2017-10-29 CRAN (R 3.4.2)              
 magrittr     1.5        2014-11-22 CRAN (R 3.4.0)              
 memoise      1.1.0      2017-04-21 CRAN (R 3.4.0)              
 methods    * 3.4.0      2017-04-21 local                       
 munsell      0.4.3      2016-02-13 CRAN (R 3.4.0)              
 papaja       0.1.0.9655 2017-11-29 Github (crsh/papaja@6958b16)
 plyr         1.8.4      2016-06-08 CRAN (R 3.4.0)              
 R6           2.2.2      2017-06-17 CRAN (R 3.4.2)              
 Rcpp         0.12.14    2017-11-23 CRAN (R 3.4.2)              
 rlang        0.1.4      2017-11-05 CRAN (R 3.4.2)              
 rmarkdown    1.8        2017-11-17 CRAN (R 3.4.2)              
 rprojroot    1.2        2017-01-16 CRAN (R 3.4.0)              
 scales       0.5.0      2017-08-24 CRAN (R 3.4.2)              
 statcheck  * 1.2.2      2016-08-18 CRAN (R 3.4.2)              
 stats      * 3.4.0      2017-04-21 local                       
 stringi      1.1.6      2017-11-17 CRAN (R 3.4.2)              
 stringr      1.2.0      2017-02-18 CRAN (R 3.4.0)              
 tcltk        3.4.0      2017-04-21 local                       
 tibble       1.3.4      2017-08-22 CRAN (R 3.4.2)              
 tools        3.4.0      2017-04-21 local                       
 utils      * 3.4.0      2017-04-21 local                       
 withr        2.1.0      2017-11-01 CRAN (R 3.4.2)              
 yaml         2.1.14     2016-11-12 CRAN (R 3.4.0)

**Comment by crsh** [comment]
Hi Peter, thanks for reporting this and sorry for the late reply. I have had trouble reproducing this problem. But I'll give it another try with your session info. I'll let you know as soon as I know more.

**Comment by crsh** [comment]
Hi Peter, I observed a pretty odd thing. I was able to reproduce this problem on a colleagues computer today (we were also looking at a different issue). It turned out that the `papaja` version on that computer wasn't up to date. After updating `papaja` and subsequently (re)installing a lot of packages that `papaja` depends on, the problem was resolved. This is the session info:

~~~
Session info -------------------------------------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.2 (2017-09-28)
 system   x86_64, mingw32             
 ui       RStudio (1.1.383)           
 language (EN)                        
 collate  German_Germany.1252         
 tz       Europe/Berlin               
 date     2017-12-13                  

Packages -----------------------------------------------------------------------------------------------------------------------------------------------------------------
 package   * version    date       source                      
 backports   1.1.1      2017-09-25 CRAN (R 3.4.1)              
 base      * 3.4.2      2017-09-28 local                       
 compiler    3.4.2      2017-09-28 local                       
 curl        3.0        2017-10-06 CRAN (R 3.4.2)              
 datasets  * 3.4.2      2017-09-28 local                       
 devtools    1.13.4     2017-11-09 CRAN (R 3.4.2)              
 digest      0.6.12     2017-01-27 CRAN (R 3.4.2)              
 evaluate    0.10.1     2017-06-24 CRAN (R 3.4.2)              
 git2r       0.19.0     2017-07-19 CRAN (R 3.4.2)              
 graphics  * 3.4.2      2017-09-28 local                       
 grDevices * 3.4.2      2017-09-28 local                       
 htmltools   0.3.6      2017-04-28 CRAN (R 3.4.2)              
 httr        1.3.1      2017-08-20 CRAN (R 3.4.2)              
 knitr       1.17       2017-08-10 CRAN (R 3.4.2)              
 magrittr    1.5        2014-11-22 CRAN (R 3.4.2)              
 memoise     1.1.0      2017-04-21 CRAN (R 3.4.2)              
 methods   * 3.4.2      2017-09-28 local                       
 papaja    * 0.1.0.9655 2017-12-13 Github (crsh/papaja@849df30)
 R6          2.2.2      2017-06-17 CRAN (R 3.4.2)              
 Rcpp        0.12.14    2017-11-23 CRAN (R 3.4.2)              
 rmarkdown   1.8        2017-11-17 CRAN (R 3.4.2)              
 rprojroot   1.2        2017-01-16 CRAN (R 3.4.2)              
 stats     * 3.4.2      2017-09-28 local                       
 stringi     1.1.6      2017-11-17 CRAN (R 3.4.2)              
 stringr     1.2.0      2017-02-18 CRAN (R 3.4.2)              
 tools       3.4.2      2017-09-28 local                       
 utils     * 3.4.2      2017-09-28 local                       
 withr       2.1.0      2017-11-01 CRAN (R 3.4.2)              
 yaml        2.1.16     2017-12-12 CRAN (R 3.4.3)
~~~

I don't think the difference in `papaja` is responsible but you could try updating. It may be worth trying to update `yaml`, too. I'd be surprised if the R version makes a difference. Could you try updating these packages (and maybe all other installed packages) and let me know if that resolves the issue?

**Comment by Grszkthfr** [comment]
Hi Frederik,

I now have the same problem mentioned above. 

From your modified template .Rmd:
> "Wilhelm-Wündt-Üniversity"

becomes
> Wilhelm-WÃ¼ndt-Ãœniversity

This behavior occured after fixing [228](https://github.com/crsh/papaja/issues/228)/[227](https://github.com/crsh/papaja/issues/227#issuecomment-403965514) with the recommended `devtools::install_github("crsh/papaja@devel")`.
Although, I am unsure that this is the critical point, as I also updated several (R and Latex) packages to try to fix it.

The difference to issue [209](https://github.com/crsh/papaja/issues/209) is, that the characters aren't lost with `papaja::apa6_docx `!

I could already narrow it down a bit to the compilation of the .tex file, as special characters are already lost in the .tex file and `$\alpha$` is shown correctly in the final .pdf file.

`rmarkdown::pdf_document()` works perfectly fine.

Here are some informations about my environment:
```
> devtools::session_info()
Session info ----------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.5.0 (2018-04-23)
 system   x86_64, mingw32             
 ui       RStudio (1.1.453)           
 language (EN)                        
 collate  German_Germany.1252         
 tz       Europe/London               
 date     2018-07-26                  

Packages --------------------------------------------------------------------------------------------------------------------
 package   * version    date       source                      
 backports   1.1.2      2017-12-13 CRAN (R 3.5.0)              
 base      * 3.5.0      2018-04-23 local                       
 compiler    3.5.0      2018-04-23 local                       
 datasets  * 3.5.0      2018-04-23 local                       
 devtools    1.13.6     2018-06-27 CRAN (R 3.5.0)              
 digest      0.6.15     2018-01-28 CRAN (R 3.5.0)              
 evaluate    0.11       2018-07-17 CRAN (R 3.5.1)              
 graphics  * 3.5.0      2018-04-23 local                       
 grDevices * 3.5.0      2018-04-23 local                       
 htmltools   0.3.6      2017-04-28 CRAN (R 3.5.0)              
 knitr       1.20       2018-02-20 CRAN (R 3.5.0)              
 magrittr    1.5        2014-11-22 CRAN (R 3.5.0)              
 memoise     1.1.0      2017-04-21 CRAN (R 3.5.0)              
 methods   * 3.5.0      2018-04-23 local                       
 papaja      0.1.0.9793 2018-07-26 Github (crsh/papaja@1a0a503)
 Rcpp        0.12.18    2018-07-23 CRAN (R 3.5.1)              
 rmarkdown   1.10       2018-06-11 CRAN (R 3.5.0)              
 rprojroot   1.3-2      2018-01-03 CRAN (R 3.5.0)              
 stats     * 3.5.0      2018-04-23 local                       
 stringi     1.1.7      2018-03-12 CRAN (R 3.5.0)              
 stringr     1.3.1      2018-05-10 CRAN (R 3.5.0)              
 tools       3.5.0      2018-04-23 local                       
 utils     * 3.5.0      2018-04-23 local                       
 withr       2.1.2      2018-03-15 CRAN (R 3.5.0)              
 yaml        2.1.19     2018-05-01 CRAN (R 3.5.1   
> rmarkdown::pandoc_version()
[1] ‘2.1.3’
```

Thanks for your help!

Best Jonas

**Comment by crsh** [comment]
Thanks, I'll take another look at this as soon as possible.

**Comment by crsh** [comment]
Okay, I think I got this fixed. Let me know if this resolves the problems for you.

**Comment by Grszkthfr** [comment]
Works again! Thanks a lot for your effort! :-)
