### ISSUE TITLE
Unable to install papaja :(

### ISSUE THREAD

**Issue by Silae92** [crsh/papaja#161]
Thank you for creating this great package, I'm really excited to used it. Unfortunately I am unable to install the papaja package (as you can see below on the attached pictures). I have to latest versions of R and R studio.

Please help!

![unbenannt](https://user-images.githubusercontent.com/34269581/33601884-e7c293e2-d9ad-11e7-94f0-38d615bf9392.png)

![papaja installation error](https://user-images.githubusercontent.com/34269581/33601810-9dbece64-d9ad-11e7-95c4-6c2a38123884.png)

**Comment by crsh** [comment]
Hi, and thanks for reaching out. I'm having trouble reproducing this. It works fine on my machine. What seems odd to me is that you get a warning saying that the DESCRIPTION file could not be found and the path that is reported has a different user name (`Sild` instead of  `Silä`). I'm not sure what's going on here. Is this problem specific to `papaja`? Can you install other R packages from GitHub?

**Comment by crsh** [comment]
If you are experiencing this problem more generally, it is probably due to the Umlaut in your user name. Also see [this discussion](https://github.com/r-lib/remotes/issues/114).

From briefly looking into this, it seems that you either could try downloading the package as .zip-file and installing it from your computer using `devtools::install()` or you could try renaming your user directory.

**Comment by Silae92** [comment]
Hi
Thank you very much for this quick response! I tried to install the papaja package from a downloaded zip-file:

> install.packages("C:/Users/Silä/Downloads/papaja.zip", repos = NULL, type = "win.binary")
Installing package into ‘C:/Users/Silä/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)

But unfortunately it did not find the file. Additionally it does not seem to be a problem specific to papaja. I tried to install another github package which did not work either. I would prefer not to rename my user directory... So, maybe you have another idea how to fix this problem?

**Comment by crsh** [comment]
You would need to unzip the folder and than use `devtools::install("path/to/unzipped/folder")`. You could also try to specify a location for your R library outside your user directory (`install.packages("package", lib = "path/to/directory")`). Other than that, I think you need to look more generally into how to fix the problem of non-ascii characters in the system user account name. That's about all I can think of. I can't really experiment with this, because I cannot reproduce this problem easily on my machine.
