### ISSUE TITLE
Updating apa_num to include option to format numbers below 10 as words

### ISSUE THREAD

**Issue by LorcanKenny** [crsh/papaja#178]
According to APA, 6th ed. words below 10 should be written as words in text, accordingly, it would be very useful to be able to instruct apa_num to output a word rather than a number in instances when the result returned is less than 10. 

A work around I've been using is:
> library(english)
> x <- c(1, 8, 15)
> a <- ifelse(x >= 10, x, as.character(english(x)))
> a
[1] "one"   "eight" "15"

**Comment by crsh** [comment]
Hi Lorcan, thanks for opening this issue. I could see this as an option for `printnum()`. The way I see it, this feature should only be available if `x` contains integers. Also, it should work for (almost) any number because numbers at the beginning of a sentence always have to be written in words rather than numerals. For these cases we also need capitalization.

To minimize dependencies, I have adapted some code I found on the R mailing list:

~~~r
printnum.integer <- function(x, numerals = TRUE, capitalize = FALSE) {
  
  if(numerals) return(x)
  
  # Based on a function that John Fox posted on the R mailing list 
  # http://tolstoy.newcastle.edu.au/R/help/05/04/2715.html
  
  number_to_words <- function(x) {
    single_digits <- c("", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine")
    names(single_digits) <- 0:9 
    teens <- c("ten", "eleven", "twelve", "thirteen", "fourteen", "fifteen", "sixteen", " seventeen", "eighteen", "nineteen")
    names(teens) <- 0:9 
    tens <- c("twenty", "thirty", "forty", "fifty", "sixty", "seventy", "eighty", "ninety")
    names(tens) <- 2:9 
    number_names <- c("thousand", "million", "billion", "trillion", "quadrillion", "quintillion", "sextillion", "septillion", "octillion", "nonillion", "decillion")
    
    digits <- rev(strsplit(as.character(x), "")[[1]])
    n_digits <- length(digits)
    if(n_digits == 1) {
      as.vector(single_digits[digits])
    } else if (n_digits == 2) {
      if (x <= 19) {
        as.vector(teens[digits[1]])
      } else {
        paste(
          tens[digits[2]]
          , Recall(as.numeric(digits[1]))
          , sep = "-"
        )
      }
    } else if(n_digits == 3) {
      paste(
        single_digits[digits[3]]
        , "hundred and"
        , Recall(collapse(digits[2:1]))
      )
    } else {
      required_number_word <- ((n_digits + 2) %/% 3) - 1
      if (required_number_word > length(number_names)) {
        stop("Number is to large.")
      }
      paste(
        Recall(collapse(digits[n_digits:(3*required_number_word + 1)]))
        , number_names[required_number_word]
        , ","
        , Recall(collapse(digits[(3*required_number_word):1])))
    }
  }
  
  collapse <- function(...) as.numeric(paste(..., collapse = ""))
  
  clean_number <- function(x) {
    x <- gsub("^\ +|\ +$", "", x)
    x <- gsub("\ +,", ",", x)
    gsub("(\ *,|-|\ +and)$", "", x)
  }
  
  if(length(x) > 1) {
    return(
      clean_number(
        vapply(x, function(y) {
          y_number <- number_to_words(y)
          substring(y_number, first = 1, last = 1) <- toupper(substring(y_number, first = 1, last = 1))
          y_number
        }
        , "a")
      )
    )
  }
  
  x_number <- clean_number(number_to_words(x))
  if(capitalize) {
    substring(x_number, first = 1, last = 1) <- toupper(substring(x_number, first = 1, last = 1))
  }
  x_number
}
~~~

Give it a try (set `numerals = FALSE`) and let me know if this is what you had in mind.

Any thoughts on this, @mariusbarth ?

**Comment by crsh** [comment]
I have pushed a commit containing this new feature to the development branch. Try installing via `devtools::install_github("crsh/papaja@devel")` and using it like so:

~~~r
printnum(1024L, numerals = FALSE, capitalize = TRUE)
~~~

**Comment by LorcanKenny** [comment]
This is amazing, thanks for doing this. I had been thinking of a logical evluation of the integer and returning a word or numeral accordingly, so that you would not need to change the command if the result changes. But I had not considered the capitalisation rule, so in this case I think manually selecting numeral and capitalisation works. Thanks again
