### ISSUE TITLE
Corresponding author

### ISSUE THREAD

**Issue by jorgesinval** [crsh/papaja#203]
If you choose the last author as the corresponding author it will appear like this:

"Correspondence concerning this article should be addressed to , & [First name Last Name]"

The ", &" should not appear

**Comment by crsh** [comment]
Hi Jorge, thanks for reaching out. I assume you are using the current version of `papaja` installed from the `master` branch (the default in `devtools`). I think I fixed this issue some time ago on the `devel` branch but due to parallel changes have not been able to release the fix on the `master` branch. Could you try installing `papaja` via `devtools::install_github("crsh/papaja@devel")` and let me know if the problem persists?

**Comment by jorgesinval** [comment]
You're absolutely right.
