### ISSUE TITLE
95% CI column prints $ symbol

### ISSUE THREAD

**Issue by josephuses** [crsh/papaja#213]
The following code chunk produces a table with $ symbols printed in the 95% CI column for `lm` in both PDF and Word outputs where there should be none.

```{r, results = 'asis'}
my_lm <- lm(Sepal.Width ~ Sepal.Length + Petal.Width + Petal.Length, data = iris)
apa_lm <- apa_print(my_lm)
apa_table(apa_lm$table, caption = "Iris regression table.")
```
![regression1](https://user-images.githubusercontent.com/3108869/40593910-4ad85bae-625e-11e8-9a1c-c2729b1839b0.png)

This is also the case for `glm`.

```{r, results = 'asis'}
my_lm <- glm(am ~ mpg + hp, family = "binomial", data = mtcars)
apa_lm <- apa_print(my_lm)
apa_table(apa_lm$table, caption = "MTCARS logistic regression table.")
```

![regression3](https://user-images.githubusercontent.com/3108869/40593934-7a7df576-625e-11e8-9be4-46630c681ae2.png)

**Comment by josephuses** [comment]
I think this is due to a redundant `paste0("$", ...)` somewhere.

**Comment by crsh** [comment]
Hi Joseph, thanks for reaching out. For this purpose, `apa_table()` takes the `escape` argument. If you use `escape = FALSE` the `$` should disappear in the output. Moreover, because this is a common question, I just pushed a commit to the development branch (install via `devtools::install_github("crsh/papaja@devel")`) that should set this option automatically for tables generated with `apa_print()`.

**Comment by josephuses** [comment]
Thanks, crsh. I appreciate the effort you are putting into this package.
