### ISSUE TITLE
Customise page margins

### ISSUE THREAD

**Issue by PenelopeLQ** [crsh/papaja#218]
Is it possible to manually change the margins using something like:
`geometry: left=38mm, right=25mm, top=25mm, bottom=25mm`
or 
`header_includes:`
`  - \geometry{left=38mm, right=25mm, top=25mm, bottom=25mm}`
in the header?

Sorry if this is misposted. Thank you very much for your help!

**Comment by crsh** [comment]
Hi @PenelopeLQ, thanks for the question. Indeed, your approach should have worked, but id didn't, due to a bug in `papaja`. I just fixed this bug, so that you should be able to use the YAML front matter parameter `geometry` to pass options as you would in any R Markdown PDF document. In other words, with the latest version of `papaja` (`devtools::install_github("crsh/papaja@devel")`) this should do the trick:

~~~yaml
geometry: left=38mm, right=25mm, top=25mm, bottom=25mm
~~~

Let me know if you experience any other problems with this.

**Comment by PenelopeLQ** [comment]
Hi @crsh Thanks so much! Your debugging did the trick.

I have a further question. It seems that the document is double-sided, so once I set the margins using `geometry: ...`, the wider margin (38mm) is on the left side on the odd pages and the right side on the even pages. I tried to make it single-sided so that the wider margin is always on the left, by adding
`classoption       : oneside`
but didn't succeed.

Could you help?

**Comment by crsh** [comment]
Interesting indeed. From the `apa6` documentation I had always assumed the document was one-sided. Since it doesn't seem like there is an option to control this behavior, you can use the `asymmetric` option of `geometry`:

 ~~~yaml
geometry: left=38mm, right=25mm, top=25mm, bottom=25mm, asymmetric
~~~

**Comment by PenelopeLQ** [comment]
Sorted. Amazing! 
Thank you for all your work. It's an amazing package. I really appreciate it.

**Comment by PenelopeLQ** [comment]
Hi @crsh 
One more issue I've noticed is that although `asymmetric` solves the problem of the text, it doesn't change the position of the running head, so the running head and page number are still at the wrong positions on even pages. Is there a way to change this?

**Comment by crsh** [comment]
Ah. According to [this answer on SE](https://tex.stackexchange.com/questions/266911/get-fancyhdr-and-geometry-to-work-nicely) this may do the trick (I currently can't try this myself):

 ~~~yaml
geometry: left=38mm, right=25mm, top=25mm, bottom=25mm, asymmetric, includeheadfoot
~~~

**Comment by PenelopeLQ** [comment]
Sorry nope. It didn't have any effects.

**Comment by crsh** [comment]
Hmm, after several attempts and some research I'm still scratching my head. I think this would be best suited as a question for [StackExchange](https://tex.stackexchange.com) as it's a LaTeX problem at this point. I'd be very interested in the solution, though.

**Comment by stefanocoretta** [comment]
This bug is back. Using papaja 0.1.0.9997, R 4.0.3, pandoc 2.11.4.
