### ISSUE TITLE
apa_table() function produces a blank page

### ISSUE THREAD

**Issue by chriscastille6** [crsh/papaja#256]
This may or may not be a papaja-specific issue, but since I'm using papaja to print to a pdf, and noticing the issue, I thought this would be a good place to start troubleshooting.

I have created tables for a manuscript. When I print to pdf, for reasons that I cannot explain, pages containing only the page number and running header are printed after the corresponding table. I suspect that others have had this issue before and am hoping that this is a simple fix. Any advice would be appreciated.

Thanks in advance!

**Comment by kbeauvivre** [comment]
Hi,
I would like to reopen this issue because I have the same problem.
What I can tell you, is that the table needs to be long enough to have the blank page. If you remove just one line of this table, there is no blank page.

Here is my reprex :

library(papaja)
efa.load = read.csv("/home/kristina/Documents/thesis/output/test.csv", header = T, sep=";")
apa_table(efa.load, label = "Tableau 2", caption="Résultats", note="N = 702", landscape = T, font_size="scriptsize")
#> <caption>(\#tab:reprex-body)</caption>
#> 
#> <caption>*Résultats*</caption>
#> 
#> 
#> 
#> A           B        D          E     F                                                        G    
#> ----------  -------  ---------  ----  -------------------------------------------------------  -----
#> aaaaaaaaa   BBBBBB   11111,11   FRE   PHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH   0.98 
#> aaaaaaaaa   BBBBBB   11111,11   FRE   PHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH   0.98 
#> aaaaaaaaa   BBBBBB   11111,11   FRE   PHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH   0.98 
#> aaaaaaaaa   BBBBBB   11111,11   FRE   PHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH   0.98 
#> aaaaaaaaa   BBBBBB   11111,11   FRE   PHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH   0.98 
#> aaaaaaaaa   BBBBBB   11111,11   FRE   PHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH   0.98 
#> aaaaaaaaa   BBBBBB   11111,11   FRE   PHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH   0.98 
#> aaaaaaaaa   BBBBBB   11111,11   FRE   PHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH   0.98 
#> aaaaaaaaa   BBBBBB   11111,11   FRE   PHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH   0.98 
#> aaaaaaaaa   BBBBBB   11111,11   FRE   PHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH   0.98 
#> aaaaaaaaa   BBBBBB   11111,11   FRE   PHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH   0.98 
#> aaaaaaaaa   BBBBBB   11111,11   FRE   PHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH   0.98 
#> aaaaaaaaa   BBBBBB   11111,11   FRE   PHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH   0.98 
#> aaaaaaaaa   BBBBBB   11111,11   FRE   PHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH   0.98 
#> aaaaaaaaa   BBBBBB   11111,11   FRE   PHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH   0.98 
#> aaaaaaaaa   BBBBBB   11111,11   FRE   PHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH   0.98 
#> aaaaaaaaa   BBBBBB   11111,11   FRE   PHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH   0.98 
#> aaaaaaaaa   BBBBBB   11111,11   FRE   PHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH   0.98 
#> aaaaaaaaa   BBBBBB   11111,11   FRE   PHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH   0.98 
#> aaaaaaaaa   BBBBBB   11111,11   FRE   PHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH   0.98 
#> aaaaaaaaa   BBBBBB   11111,11   FRE   PHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH   0.98 
#> 
#> <center>*Note.* N = 702</center>
