### ISSUE TITLE
Figures and tables in correct locations in PDF

### ISSUE THREAD

**Issue by fedebul** [crsh/papaja#263]
I have been using papaja to write up a manuscript, and am having a hard time getting tables and figures to appear in text, where they are supposed to, without appearing in the middle of paragraphs. 

I am attaching an .rmd file and the knit pdf that reproduces this issue. The first two tables appear where they should, but then the Figure 1 appears at the top of the next page, in the middle of a paragraph, and the following tables and figures do not appear where they should, some even going after the discussion, and in the middle of the references. Any advice on the correct fig.pos or placement options to get the tables and figures in text, where they are supposed to appear, without breaking up paragraphs?

Thank you! 

[Archive.zip](https://github.com/crsh/papaja/files/2822539/Archive.zip)

**Comment by fedebul** [comment]
Hi, thanks! I have tried fig.pos = '!h', with out.width = '', out.height = '50%', and fig.align = "center", and each one puts the figure at the top of the next page, breaking up a paragraph.

**Comment by crsh** [comment]
LaTeX, by default, places floats (figures and tables) either at the top or bottom of pages close to where they are placed in the source file. The exact placement is chosen to best use the available space. This is generally considered a feature rather than something to prevent. You can force LaTeX to give up on saving space with different persuasive power. The placement option `H` should do the trick here.

~~~r
apa_table(tabyl(iris$Species, iris$Sepal.Length), caption = cap, col_spanners = NULL, digits = 0, placement = "H")
~~~

In your attached example, you don't set any of the above mentioned additional options for figures. The following should work.

~~~r
```{r figure2, echo=FALSE, fig.cap = cap, fig.pos='H', out.width="\\textwidth"}
ggplot(data =iris, aes(x = Species, y=Petal.Length)) + geom_boxplot() + geom_point()
cap <- sprintf("Figure 2 caption")
```
~~~

**Comment by crsh** [comment]
Does this resolve this issue for you?

**Comment by mvanaman** [comment]
I'm not the OP, but I can say that I had an identical problem and the suggestion `placement = "h"` worked for me!
