### ISSUE TITLE
Including tex header removes affiliation from document

### ISSUE THREAD

**Issue by plogacev** [crsh/papaja#265]
When a .tex file is included via the "includes" argument embedded under "output", the author affiliation is omitted in the .tex file, and the document comes out without affiliation. This is true even when the included tex header is empty. See the attachment .zip file for two minimal examples: One produces a document with an affiliation, the other one omits it!

[minexample_affiliation.zip](https://github.com/crsh/papaja/files/2861700/minexample_affiliation.zip)

**Comment by crsh** [comment]
This is, unfortunately, a [known issue](https://github.com/rstudio/rmarkdown/issues/1359) in `rmarkdown`/`pandoc`. Because `papaja`'s tempalte utilizes `header-includes`, I'm hoping that it will be fixed there so that I don't have to hack a workaround. Can you add the contents of the TeX file to `header-includes`?
