### ISSUE TITLE
Single-spacing does not work with longtable

### ISSUE THREAD

**Issue by danawanzer** [crsh/papaja#273]
Longtables do not seem to work with the single-spacing YAML code. I have to wrap my code with the following to make it work:
```
\begin{singlespace}
\end{singlespace}
```

[Test.txt](https://github.com/crsh/papaja/files/2950147/Test.txt)
[Test.pdf](https://github.com/crsh/papaja/files/2950148/Test.pdf)

(I hope this is a reproducible example to work with. I'm not so good at doing this myself and I did the best I could. Note that I couldn't upload an Rmd file so I uploaded as a txt which I think should be able to convert to Rmd.)

**Comment by crsh** [comment]
Hi Dana, thanks for reaching out with a reproducible example. Since the GitHub issues here are intended for bug reports or feature requests and you are asking a question about papaja and LaTeX, would you mind post this as a question on [StackOverflow](https://stackoverflow.com/questions/tagged/papaja)? I'll be sure to post an answer as soon as possible. That way the answer will be more discoverable and hopefully help others having the same problem.

**Comment by danawanzer** [comment]
Apologies for the late response, I just posted on StackOverflow!
