### ISSUE TITLE
Remove spacing around headings and R chunks

### ISSUE THREAD

**Issue by danawanzer** [crsh/papaja#274]
I think this is an issue with LaTeX in general, but it's not really APA style so I'm hoping there's something that can be done to improve it.

Essentially, there are always extra spaces in my document, especially around headings and R chunks. 

I've attached my Rmd and my PDF to see examples. To be clear where the issues are:

- On page 3, you can see there's extra line spacing around Heading 1 "What is evaluation?"
- On page 9, you can see extra line spacing around "Methods" and "Procedures"
- Starting on page 10, there is extra spacing around nearly every paragraph because of the R chunks that are in between paragraphs

Rather, everything should simply be double spaced with no extra buffered space around headings. This helps especially with page counts, which my main journal cares more about than word count :) 

Removing extra spaces after paragraphs or extra lines in the Rmd file does not seem to improve things. Adding "\raggedbottom" to the document helps slightly.

[00_Wanzer_2019_Manuscript.pdf](https://github.com/crsh/papaja/files/2950154/00_Wanzer_2019_Manuscript.pdf)
Link to the Rmd file since I can't upload that directly: https://www.dropbox.com/s/2vhsnknnoy7xkg2/00_Wanzer_2019_Manuscript.Rmd?dl=0

**Comment by crsh** [comment]
After removing all code chunks I cannot run due to missing files I knitted the R Markdown file and I'm not getting any of the extra white space when using `noextraspace` and `\raggedbottom` as you are:

---

<img width="630" alt="Bildschirmfoto 2019-03-12 um 22 16 26" src="https://user-images.githubusercontent.com/2195485/54236891-090d3100-4515-11e9-95ce-6513f9b6b678.png">

---

<img width="622" alt="Bildschirmfoto 2019-03-12 um 22 16 37" src="https://user-images.githubusercontent.com/2195485/54236920-17f3e380-4515-11e9-8039-f054eb22c70c.png">

---

I'm not sure what's going. Could this may be related to your LaTeX setup?

**Comment by danawanzer** [comment]
Yeah, I have noextraspace defined in my YAML and the \raggedbottom at the top of my manuscript but I'm still getting a slight extra space around headings. If it is something to do with my LaTeX setup, what would I do to fix it? I'm on a Windows PC if that makes a difference.

**Comment by crsh** [comment]
To be honest, I'm not sure. Sorry. But at this point I suspect this behavior is unrelated to `papaja`. I would suggest to post this question to [StackOverflow](https://tex.stackexchange.com/). Someone there may be able to help.

**Comment by vvader24** [comment]
I am having the same issue. Is there any way I could resolve this quickly?
