### ISSUE TITLE
Appropriate Diacritic Characters in render_appendix

### ISSUE THREAD

**Issue by AlexChristensen** [crsh/papaja#283]
**Is your feature request related to a problem? Please describe.**
When using `render_appendix`, all of my diacritic characters of my citations in the appendix section are not appearing as they should.

In the main text, they appear like this: (M**õ**ttus & Allerhand, 2017)

(Bold added for emphasis)

And it's reference section:
M**õ**ttus, R., & Allerhand, M. (2017). Why do traits come together? The underlying trait and
network approaches. In V. Ziegler-Hill & T. K. Shackelford (Eds.), SAGE handbook
of personality and individual differences: The science of personality and individual
differences (pp. 1–22). London, UK: SAGE Publications.

In the appendix, this same citation appears like this: (M**Ãµ**ttus & Allerhand, 2017)

And it's reference section:
M**Ãµ**ttus, R., & Allerhand, M. (2017). Why do traits come together? The underlying trait
and network approaches. In V. Ziegler-Hill & T. K. Shackelford (Eds.), SAGE
handbook of personality and individual differences: The science of personality and
individual differences (pp. 1–22). London, UK: SAGE Publications.

**Describe the solution you'd like**
I would like the diacritic characters to be the same in the appendix as they are in the main text -- that is, **õ** should appear as **õ** and not **Ãµ**

**Describe alternatives you've considered**
I've considered trying to manually change the encoding to be UTF-8 in the appendix section because I believe that this may be the source of the issue. In all my attempts, however, I have not been able to successfully do this. Here's what I've tried:

- Specifically including `\usepackage{inputenc}[utf8]` in the `includes-header:` section
- Including `\usepackage{inputenc}[utf8]` in the appendix Rmarkdown file
- Including `options(encoding = "utf-8)`
-- in `{r render_appendix, include = FALSE} render_appendix("PPN_SI.Rmd") options(encoding = "utf-8")`
-- in the appendix Rmarkdown file

**Comment by crsh** [comment]
Hi Alex, thanks for the report and sorry for taking so long to respond. I tried to reproduce this on my machine but I'm having some trouble. Two quick questions to help me locate the problem:

1. Are you experiencing this issue on a Windows machine?
2. Have you tried using the [YAML front matter option `appendix`](https://crsh.github.io/papaja_man/writing.html#appendices) instead of calling `render_appendix()` in a code chunk?

**Comment by AlexChristensen** [comment]
Hello,

No problem on taking a while -- I appreciate all your work on this great package. I've been using it for all of my writing since I crossed over.

I used a temporary workaround for submitting the manuscript (creating a separate papaja .pdf and removing the first to pages). 

1. I am using a Windows computer.

2. I have tried using the YAML front matter option -- in fact, it's already in the document (at the end of the document). When removing `render_appendix()`, then the build errors out.

I've emailed the files necessary for constructing the documents.

Thank you!
Alex

**Comment by crsh** [comment]
Thanks! I just tried it on my machine and it works as expected. As I expected, this seems to be a problem specific to Windows. I'll need to try it on another computer. Let me get back to you.

**Comment by einGlasRotwein** [comment]
Hey Frederik,

1. I am using Windows as well.
2. Using appendix in the YAML header instead of `render_appendix` works in terms of generating the document with an appendix, but the German "umlauts" are still messed up.

You probably already know this (sorry if this is redundant information), but on Windows, including e.g. plots generated from a different script in an rmarkdown document will destroy special characters, unless encoding is explicitly specified. I uploaded a small example [here](https://github.com/einGlasRotwein/bits-and-pieces/tree/master/Umlauttest). So the issue is how to "tell" R that the encoding of the appendix is UTF-8 - seems like Alex already tried all the ways one could think of to achieve this.

**Comment by crsh** [comment]
Hi @AlexChristensen, hi @einGlasRotwein,

I finally made some time to look into this and I think I fixed the problem. It should now work simply by adding `appendix: appendix.Rmd` to the YAML front matter.

**Comment by AlexChristensen** [comment]
Works perfectly! Thanks, Frederik!

**Comment by einGlasRotwein** [comment]
Doesn't work for me, but it seems to be a different issue since umlauts now get messed up on my title page as well. If it works for Alex, the problem must have something to do with my settings; I'll try and figure out what it is.
