### ISSUE TITLE
apa_table

### ISSUE THREAD

**Issue by ccobserver** [crsh/papaja#34]
Do I need to do anything in addition to installing papaja to get the apa_table function to work? I get the following error when I try and run your code from the example document (i.e., cars descriptives):

Error in apa_table.latex(...) : could not find function "validate"

It is for this reason that I've been trying to use LaTeX code to create a table. A second problem of mine, however, is I don't know where to add \usepackage{}. For example, with the table I've tried \usepackage{adjustbox} or tabularx, as suggested by you, but I get an error.

**Comment by crsh** [comment]
Sorry once again for the late reply, I was at a conference last week.

To answer your second question first, there are two ways to load additional LaTeX packages, or customizing the preamble more generally. See this [related SE question](http://tex.stackexchange.com/questions/171711/how-to-include-latex-package-in-r-markdown) for examples.

I don't have a ready answer to your second question. If you installed papaja from this repository the function `validate` should have been installed alongside all other functions of the package (`validate` is not exported but that really should make a difference). Did you install the package following the instructions in the [Readme](https://github.com/crsh/papaja)? If so, could you try reinstall the package following the same instructions and let me know if you keep getting this error?

**Comment by ccobserver** [comment]
I tried reinstalling. When I require("papaja"), I get this:

>require("papaja")
Loading required package: papaja

Attaching package: ‘papaja’

The following objects are masked _by_ ‘.GlobalEnv’:

     apa_table, apa_table.latex, apa_table.word

**Comment by crsh** [comment]
It appears you have sourced some of these functions from the packages source files and they are part of your global environment. When they are, the unexported function `validate` cannot be found, because it is not part of the global environment (where R is looking for it), but only available to functions inside the papaja-package. The functions you created in your global environment by sourcing the R-files are not explicitly associated with the package, though.

To fix this issue, either clean your workspace, or explicitly remove the sourced functions

  rm("apa_table", "apa_table.latex", "apa_table.word")

This should do the trick. Let me know if this helps.

**Comment by ccobserver** [comment]
I used rm(list = ls()) to clean workspace. That worked. Thank you for the help!
