### ISSUE TITLE
Results from Stats: pairwise comparisons

### ISSUE THREAD

**Issue by PauloBoggio** [crsh/papaja#340]
Congrats for creating papaja. I am writing my first paper using it... having lots of fun.

I have some pairwise comparisons and would like to report in apa style, but I did't find a way using apa_print(). Is that possible.

I have a dataframe with a column with the participants responses ('ratings') and another column with the conditions. I run the followed code to compute the pairwise comparisons and would like to report the p values along the manuscript in apa style.

pairwise.t.test(df$rating, df$condition, pair=TRUE, p.adj = "bonf")

Any suggestion? Thanks

**Comment by crsh** [comment]
Hi Paulo, `pairwise.htest`-objects are currently not supported. To be honest, I'm not sure this is worth the effort because the output is really minimal (e.g., it does not provide *t*-values or *df* to assamble a complete string for reporting). It is, however, easy to report the whole table. You can adapt the following example to your needs:

~~~r
library("papaja")

airquality$Month <- factor(airquality$Month, labels = month.abb[5:9])
pw_month <- (pairwise.t.test(airquality$Ozone, airquality$Month))

apa_table(
  printp(pw_month$p.value)
  , caption = "Pairwise comparisons of monthly air quality"
)
~~~

If you want to add stars or highlight the significant ones in any other way, you can adapt the code in [this question](https://github.com/crsh/papaja/issues/210#issue-322175286).
