### ISSUE TITLE
Character encoding of abstract and note sections in MS Word

### ISSUE THREAD

**Issue by ctreffe** [crsh/papaja#35]
When knitting the standard papaja template to a .docx file non-ascii characters (I tested ÄÜÖäüöß€) in the abstract and the note sections of the word document are seemingly not encoded correctly. The same characters are displayed properly when used in the title or outside the header in the normal document text. Characters are also displayed properly in the two sections when knitting a pdf file. 

I am using MikTex 2.9.5105 and the latest development version of papaja. To view the .docx file I use MS Word 2013.

**Comment by crsh** [comment]
Hi @ctreffe,

thanks for letting me know and sorry for the late reply, I was at a conference last week. I have located the source of the problem, but I'm not quite sure how to fix this. The problem seems to be character encoding in some parts of the `rmarkdown` package. I'm not sure whether I can fix this or whether this is an issue that needs to be passed on to the folks at RStudio, but I'll take a closer look at this in the next days.

For now what you can do is replace the characters by [HTML entities](http://unicode.e-workers.de/entities.php), e.g., ö = `&ouml;`, ä = `&auml;` or Ü = `&Uuml;`.

I'll let you know as soon as I know more.

**Comment by crsh** [comment]
I was able to pin down the problem and it is related to the encoding of special characters in the YAML header on Windows; it is not directly related to papaja. I have alerted the developers of the rmarkdown-package to the problem. Thanks again for pointing this out.

**Comment by crsh** [comment]
Just as a quick update: The problem will be fixed in one of the next releases of the rmarkdown package. Thanks again for reporting.
