### ISSUE TITLE
Summary and apa_print() methods for within-subjects confidence intervals

### ISSUE THREAD

**Issue by JeffreyRStevens** [crsh/papaja#362]
I very much like the `within_subjects_conf_int` (`wsci`) function. But I find it cumbersome to have to calculate the means separately. Moreover, when `wsci` removes subjects because of NAs, this makes means calculated by `summarise` with `na.rm=T` or with missing data not applicable to the statistics calculated by `wsci`.

Would it be possible to include a column (or an option for one) in the output of `wsci` for the means (and perhaps standard deviation and upper and lower confidence limits)?

**Comment by mariusbarth** [comment]
Hi Jeffrey, I just pushed a possible solution to the development branch (install via `devtools::install_github("crsh/papaja@devel")`.

```
library(papaja)
summary(wsci(data = npk, dv = "yield", id = "block", factors = c("N", "P")))
```

Tell me what you think about it.

**Comment by jstevens5** [comment]
Marius, thanks so much for your quick turn around on this! This looks great and is exactly what I had in mind. I especially like that it labels the columns based on the statistic rather than just inheriting the label from the `dv` argument. 
The only other issue is whether it should also return the intervals. Most of the time, I would prefer having the upper and lower limits that you've computed (for importing to plots), but sometimes I may want the intervals (for describing in text).
Thanks!

**Comment by mariusbarth** [comment]
Ah, ok! I had plotting in mind, but reporting in text is also a very interesting use case... it sounds to me like I should write something that is consistent with `apa_print()`, but for descriptives.

**Comment by mariusbarth** [comment]
Hi Jeffrey, on the development branch, there is now also an `apa_print()` method for within-subjects confidence intervals which should do what you had in mind. You can use the following lines of code if you want to see it in action. If you have feedback, it is highly appreciated:
```
remotes::install_github("crsh/papaja@devel")
library(papaja)
apa_print(wsci(data = npk, dv = "yield", id = "block", factors = c("N", "P")))
```

**Comment by jstevens5** [comment]
Marius, this is great--many thanks!

**Comment by mariusbarth** [comment]
Hi @crsh. With the latest additions to the development branch, I think this feature is now ready.
