### ISSUE TITLE
Option to cut values below a threshold in tables

### ISSUE THREAD

**Issue by bjorn-persson** [crsh/papaja#371]
I can't figure out how to selectively print values in a table above or below some value. What I'm looking for is known as "cut" in Revelle's psych package. MWE below.

```
library("psych")
library("psychTools")
derp <- fa(ability, nfactors=3)
print(derp, cut=0.5) #removes all loadings smaller than 0.5
derp <- print(derp, cut=0.5) #apa_table still doesn't print like this
```

Question is, how do I add that cut to a apa_table? Printing apa_table(derp) prints the entire table, including all values.

**Comment by crsh** [comment]
Hi Björn, this is because the `print`-method from `psych` does not return the formatted loadings but only the table of variance accounted for. You can, however, get the result you want by manually formatting the loadings table. Given that this is a question related to the use of `papaja`, would you mind asking this as a question on StackOverflow using the [papaja-tag](https://stackoverflow.com/questions/tagged/papaja)? I'll give you the long answer over there.

**Comment by bjorn-persson** [comment]
Of course, posted @ https://stackoverflow.com/questions/62018314/option-to-cut-values-below-a-threshold-in-papajaapa-table

**Comment by crsh** [comment]
Excellent thank you.
