### ISSUE TITLE
problems with papaja::apa6_word 

### ISSUE THREAD

**Issue by samirnemechaves** [crsh/papaja#382]
**Describe the bug**
I try to create a word document in papaja, I updated already my papaja,  but I have problems with this, and I have noticed something if  I create the R-markdown in the computer desktop, papaja::apa6_word work it, but if I create the  R markdown in another folder, for example in a R-project, papaja::apa6_word crash it

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/32044038/85041761-fd64dd00-b14f-11ea-8169-badea4f1661d.png)
![image](https://user-images.githubusercontent.com/32044038/85041673-e45c2c00-b14f-11ea-9066-3cc762724ce8.png)

**Additional context**
mi wd: "C:/Users/amigp/OneDrive/Documentos/Santo Tomás/Formación docente/Cienciometria/DataWOS/BibliometrixUSTA"

**Comment by crsh** [comment]
Hi Samir, thanks for reaching out. I'm having a hard time understanding when exactly this error occurs; I haven't been able to reproduce it. Could you provide some details (e.g., in your "To Reproduce" section)? Are you using the current development version (`remotes::install_github("crsh/papaja@devel")`)?

**Comment by samirnemechaves** [comment]
Hi, crsh, thanks for your response. I have the papaja current version.... 

My problem is: 

I have seen that if I save the R- Markdown document on the desktop, and I give the order to knit it, the document is compiled and created without problems, in word document format. but if I create an R-markdown and save it in another place (e.g an R-project, with a different location than the desktop directory ), and I give the order to knit it, the document is not compiled ... it is only compiled if I create a pdf document

thanks for your attention

**Comment by crsh** [comment]
Thanks for the added detail. This is has me scratching my head. The problem is the post processor in the DOCX format. It modifies the DOCX archive to add the correct running head. After applying the fix, [it rezips the contents](https://github.com/crsh/papaja/blob/60870d8716f681f3185a013013b8706085d4db4a/R/apa6_formats.R#L280).

I suspect that the special characters on your file path causes `zip::zipr()` problems (see https://github.com/r-lib/zip/issues/53). To confirm this suspicion could you try creating a test-zip-archive in your project directory (`BibliometrixUSTA`) using `zip::zipr()`? If this is indeed the case, there is nothing I can do about this other than wait for an update of `zip` that fixes this bug.

For now, you could try removing the special characters from the file path.

**Comment by samirnemechaves** [comment]
I removed the special characters and it worked it !!!

Thanks for your help
