### ISSUE TITLE
Consistently add df to column labels if invariant

### ISSUE THREAD

**Issue by crsh** [crsh/papaja#409]
Currently, degrees of freedom are handled somewhat inconsistently in `apa_result_table`s. For example, for `lm` objects the degrees of freedom are the same for all coefficients. Instead of a redundant column, the degrees of freedom are added to the label of the `statistic` colum (`$t(13)$`). This is, however, not true for all methods (e.g., the recently developed HLM methods), which seems inconsistent to me.

I think it would be nice to have an internal workflow that checks if the degrees of freedom are the same for all rows of the table and, if so, adds them to the label. Would you agree @mariusbarth?

**Comment by mariusbarth** [comment]
While implementing the new HLM methods (and also while implementing the `htest` method) I also wondered how to handle this with the highest consistency. However, in both cases I opted for a separate column for degrees of freedom for the following reasons:

- For `htest` objects, I tried to imagine in which situation a user might decide to use the table output, and concluded that it would most likely be in cases when one wants to combine the results from multiple tests in one table. For such cases, a separate column seems to be desirable because the tests will most likely have different numbers of degrees of freedom.
- For HLMs, degrees of freedom might be present for Satterthwaite or Kenward-Roger degrees of freedom, or for output from `afex::mixed` (Satterthwaite, Kenward-Roger, or chi-squared dfs for likelihood-ratio tests). For both df approximations, the dfs are most frequently not exactly equal, while being *equal after rounding* in a substantial number of cases. I had the impression that putting the df in the variable label would falsely imply that dfs are exactly equal. Moreover, if we checked for approximate equality, the structure of the output table would depend on the data, which I think is undesirable because users will be confused.

One more thought: For between-subjects 2x2 ANOVA, there should also always be the same number of degrees of freedom in all rows, but I think keeping the layout similar (redundant df columns) for all types of ANOVA is highly desirable.

In contrast, I think for (generalized) linear models there really is no need for an extra column for dfs.

**Comment by crsh** [comment]
Make it optional by user argument with defaults potentially varying across methods.

**Comment by crsh** [comment]
With the recent addition of `transmute_df_into_label()` I think we can close this isse, @mariusbarth?

**Comment by mariusbarth** [comment]
True
