### ISSUE TITLE
When abstract is long (300 words), the word "Abstract" appears on the cover page

### ISSUE THREAD

**Issue by mahowak** [crsh/papaja#41]
In "doc" mode, when the abstract is long (~300 words), just the word "Abstract" appears on the first page and the rest appear on page 2. It makes it look like the abstract section has no title. Inserting a pagebreak in the tex file does not fix this.

**Comment by crsh** [comment]
As far as I can tell right now, this problem is caused by the LaTeX class apa6 that `papaja` uses. I was able to get the heading of the abstract on the next page by adding `\newpage` to the end of the note in the tex file. This does not quite work from within the Rmd-file, yet. I will take a closer look at this as soon as I can.

**Comment by crsh** [comment]
So, if you can go without the automatically generated correspondence line at the end of the author note, set `corresponding: no` in the header and add `\newpage` to the end of your author note. When I do this, the abstract---including the heading---is pushed to the second page. Let me know if that works for you.

**Comment by mahowak** [comment]
That did the trick. Thanks.

While I'm writing: the latest version of pandoc breaks \tightlist in
various Rmarkdown templates including papaja. I was able to fix it by
adding this fix to the template:
https://github.com/therealmarv/phd_thesis_markdown/commit/ef180985bcd829de8e61f8767d372cbfc32030c5

**Comment by crsh** [comment]
Thanks for the heads-up. I added the lines to the template.
