### ISSUE TITLE
`cite_r()` does not escape semicolons and lead to incorrect citations

### ISSUE THREAD

**Issue by marklhc** [crsh/papaja#442]
**Describe the bug**
The output of `cite_r()` include a parenthetical citation with a version number followed by a semicolon. However, since a few months ago, I notice that the citation is not rendered correctly in pandoc 2.11.4, without escaping the semicolon. Not sure whether it's just on my computer or not. 

**To Reproduce**
``` r
library(papaja)
papaja::cite_r()
#> [1] "R [Version 4.0.4; @R-base]"
```

<sup>Created on 2021-03-06 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Expected behavior**
If I escape the semicolon with `R [Version 4.0.4\; @R-base]` directly, it gives the correct citation. 

**Screenshots**
With `cite_r()`
![image](https://user-images.githubusercontent.com/6175332/110222351-7646c900-7e86-11eb-8514-9c3ceb21c3e6.png)
With `R [Version 4.0.4\; @R-base]`
![image](https://user-images.githubusercontent.com/6175332/110222466-39c79d00-7e87-11eb-89a9-20e5366bd64c.png)

**Comment by crsh** [comment]
Hi Mark, thanks for documenting this. What version of `pandoc` are you using?

**Comment by crsh** [comment]
Okay, I just pushed a commit to the development branch, that should fix this issue. Try `remotes::install_github("crsh/papaja@devel")`. :)

**Comment by AlexChristensen** [comment]
If I may tag along, I found that the development version fixed the `cite_r()` issue. `pandoc 2.11.4`. 

#### Describe the bug
I'm noticing that the semi-colon needs to be escaped now when including words with a citation. This seems like a new behavior that I wasn't aware of. I last used `papaja` to knit a manuscript at the end of January and don't recall this occurring.

#### To Reproduce (screenshot)
Any words that are bracketed with a citation and separated with a semi-colon are output as the top citation in the screenshot. Words separated by a comma like [e.g., @kaiser1960application] works: (e.g., Kaiser, 1960).

![image](https://user-images.githubusercontent.com/32655669/111625092-db71b700-87c2-11eb-9823-81c3114b57a0.png)

#### Expected behavior
Words would be placed in parentheses in the citation like the bottom citation in the screenshot.

I'm okay with escaping the semi-colon; however, I wasn't sure whether this is a desired behavior.

Thanks,
Alex

**Comment by marklhc** [comment]
Thank you @crsh, the devel version fixes this. 

@AlexChristensen, I think the need to escape semicolon is related to some changes in pandoc-citeproc, not with `papaja`. [This issue](https://github.com/jgm/pandoc-citeproc/issues/271) may be relevant. I'm not sure why it only showed up recently on my computer as this behavior seems to have been described a while ago.
