### ISSUE TITLE
Prune dependencies by removing modelling packages?

### ISSUE THREAD

**Issue by LukasWallrich** [crsh/papaja#464]
Thanks for this package - I am just finishing the first manuscript, and very much appreciate being able to stay in R! 

However, I just switched to a new computer and installed papaja - and was shocked by the number of dependencies. As I understand it, all the modeling packages that are suggested (e.g., BayesFactor and lme4, which each come with their own list of dependencies) are only needed when such models are reported? Is it then necessary to install all of them just to use papaja? (That approach would seem to indicate that broom should suggest a lot of packages as well, which it does not ... but maybe I'm overlooking something.)

**Comment by mariusbarth** [comment]
Hi @LukasWallrich,

installing packages such as **BayesFactor** and **lme4** is indeed something that should not happen automatically when **papaja** is installed. R's package dependency system distinguishes three different types of dependencies: "Depends", "Imports", and "Suggests". 

*Depends* are packages that **papaja** needs to work and are loaded whenever papaja is loaded (these are only R itself and **tinylabels**, which used to be a part of **papaja**). *Imports* are packages that are needed by **papaja** to work properly, but that are not loaded when **papaja** is loaded. *Suggests* are packages that are not needed by **papaja** to work, but some examples or packages tests will make use of them (most likely because we support modelling results from these packages). 

Packages **BayesFactor** and **lme4** are listed as *Suggests* in **papaja**'s `DESCRIPTION` file, and such packages should not be installed by `install.packages()` or `remotes::install_github()` (which is indeed the default for both functions).

I just tried to install **papaja** in a fresh docker container, and it worked as expected (only packages from *Depends* and *Imports* were installed):
```
> remotes::install_github("crsh/papaja@devel")
Downloading GitHub repo crsh/papaja@devel
Installing 42 packages: mime, xfun, utf8, crayon, cli, pkgconfig,
fansi, pillar, R6, generics, cpp11, vctrs, tidyselect, tibble,
rlang, purrr, magrittr, lifecycle, glue, ellipsis, dplyr, stringi,
markdown, highr, base64enc, digest, stringr, tinytex, jsonlite,
evaluate, htmltools, yaml, knitr, rmarkdown, assertthat, tidyr,
backports, zip, rmdfiltr, broom, bookdown, tinylabels
```
I suspect that in your case, `remotes::install_github()` for unknown reasons additionally installed packages from the *Suggests** field, which would explain the overly hefty install. I suspect that this is a bug in `remotes::install_github()`.

From a **papaja** perspective, I think this is one more reason to make **papaja** available from CRAN as soon as possible, so that **papaja** can finally be installed via base R's `install.packages("papaja")`, this will hopefully put an end to such problems. But if you can reproduce the problem on your computer (possibly by removing all installed packages and then re-installing **papaja**), this problem should be reported as a bug to [the package maintainers of the **remotes** package](https://github.com/r-lib/remotes).

**Comment by crsh** [comment]
Thanks for the comprehensive explaination, @mariusbarth. It is worth pointing out that both `install.packages()` and `remotes::install_github()` should install packages listed in `Suggests` only when using `dependencies = TRUE` (see `?install.packages`).

> (That approach would seem to indicate that broom should suggest a lot of packages as well, which it does not ... but maybe I'm overlooking something.)

From looking at `broom`'s `DESCRIPTION` it, indeed, contains a long list of suggested packages: https://github.com/tidymodels/broom/blob/master/DESCRIPTION

We could, in principle, list packages that define classes, for which we provide methods as `Enhances`, but then we couldn't run any tests on these methods, which seems undesirable.

**Comment by mariusbarth** [comment]
In the long term, I think we could adopt an approach that would also (partially) address #396: We could create a separate package that contains `apa_print()` (with generic and methods). **papaja** would only re-export the generic (or we add the extra package to *Depends*)

That way, you could install **papaja** with its own *Suggests*, but without the *Suggests* of this extra package by using

```
install.packages("papaja", dependencies = TRUE)
```

Here is the corresponding documentation:

> TRUE means to use c("Depends", "Imports", "LinkingTo", "Suggests") for pkgs and c("Depends", "Imports", "LinkingTo") for added dependencies: this installs all the packages needed to run pkgs, their examples, tests and vignettes (if the package author specified them correctly).

**Comment by LukasWallrich** [comment]
Thank you for clarifying this. I used `pacman::p_load_gh()` as a wrapper around `remotes::installgithub()` ... but that changes the `dependencies` default, which I had never noticed so far. I should have checked that before posting here - including them as `Suggests` is obviously sensible, but I agree with @mariusbarth that this might be another reason for splitting the package.
