### ISSUE TITLE
More lightweight github actions

### ISSUE THREAD

**Issue by mariusbarth** [crsh/papaja#478]
It is extremely annoying that our package checks repeatedly fail because in the github workflow, **pak** tries to install Suggests of Suggests (recursively), which results in a giant dependency tree. I think we should try to switch to [r-ci](https://github.com/eddelbuettel/r-ci).

**Comment by crsh** [comment]
To be honest, I don't understand what changes this would imply. But here's an idea how we might retain what we currently have (for better or worse): As far as I understand, the problem is that `pak`, by default, recursevly installs Suggests, right? As far as I understand, this is specified [here](https://github.com/r-lib/actions/blob/0b468bae2ad53083dd2f475122202e8db2986d46/setup-r-dependencies/action.yaml#L21) in the `r-lib` GitHub actions workflow.

If I understand the documentation correctly, it should be possible to do the following:

~~~r
deps <- pak::pkg_deps("local::.", dependencies = list(direct = TRUE, indirect = NA))
saveRDS(deps, ".github/r-depends.rds")
~~~

This should include suggests for `papaja` but not for any of its depends, imports, or suggests. If this works, would you still want to switch to `r-ci`?

**Comment by mariusbarth** [comment]
Hi @crsh, unfortunately, this type of specifying dependencies does not seem to work. Maybe it is worth filing an issue at r-lib/pak before trying to switch.

**Comment by crsh** [comment]
I did not understand the documentation correctly. The following works:

~~~r
deps <- pak::pkg_deps(
  "local::."
  , dependencies = list(
    direct = pkgdepends::pkg_dep_types()
    , indirect = pkgdepends::pkg_dep_types_hard()
  )
)
~~~

This would also install `Enhances`-packages, but we don't have any of those, so it doesn't matter.

**Comment by mariusbarth** [comment]
Perfect, thanks for taking a look into it!

**Comment by mariusbarth** [comment]
These two function seem to output simple vectors:
```
> dput(pkgdepends::pkg_dep_types_hard())
c("Depends", "Imports", "LinkingTo")
> dput(pkgdepends::pkg_dep_types())
c("Depends", "Imports", "LinkingTo", "Suggests", "Enhances")
```
So maybe this would be enough:
```
deps <- pak::pkg_deps(
  "local::."
  , dependencies = list(
    direct = c("Depends", "Imports", "LinkingTo", "Suggests")
    , indirect = c("Depends", "Imports", "LinkingTo")
  )
)
```

**Comment by crsh** [comment]
Sure, works for me and does not rely on the `pkgdepends` package. 👍

**Comment by crsh** [comment]
Just to be sure we are on the same page: Would you be willing to make the discusse changes to the workflow (given that you set it up in the first place)?

**Comment by mariusbarth** [comment]
Does the code above work on your local machine? It breaks on my machine with an incomprehensible error message.

**Comment by mariusbarth** [comment]
Seems to work now. Maybe we move check on R-devel to a separate github action that uses more-traditional dependency installation. Think this will be more robust.

**Comment by mariusbarth** [comment]
I think we can safely close this issue. Seems to work for now and I don't have a better idea than to use the stuff from r-ib/actions
