### ISSUE TITLE
Failing test because of breaking change in effectsize

### ISSUE THREAD

**Issue by crsh** [crsh/papaja#483]
Our tests are failing, among other things, because `effectsize` has recently introduced a [breaking change](https://github.com/easystats/effectsize/blob/main/NEWS.md): confidence intervals for variance explained effect sizes now are one-sided 95% CI (see the discussion [here](https://github.com/easystats/effectsize/pull/366)). I find the argument for this change quite compelling, although it would be a breaking change in `papaja`, too. Also, I share the worry that it's quite confusing to users. If we follow their lead, we need to make a note of it in the documentation. Any thoughts, @mariusbarth?

**Comment by mariusbarth** [comment]
I think

a) it is confusing to users,
b) breaks with convention how variance-explained effect sizes (e.g. R-squared) are typically reported (I never saw anything but 90% CIs in the past)
c) assumes that all reviewers are stupid, but will always insist on being smarter than the author,
d) is perfectly consistent with the NHST, which renders it redundant,
e) obfuscates the information that Joachim Vandekerckhove likes about CIs: https://twitter.com/VandekerckhoveJ/status/1444188357194489863

**Comment by mariusbarth** [comment]
> I'm not sure I understand why a consistent CI is redundant with the p-value. It's, of course, a transformation of p but the transformed value is informative about the scale of the statistic we are interested in (lower bound of variance explained).

I think against the backdrop of this argument it is pretty clear that it is not a good idea to provide an upper boundary of 1, because this is clearly misleading.

> Also, I'm not sure that I'm comfortable to suggest that users should interpret the CI as posterior interval.

We should indeed not suggest that, it is only a quick and dirty approximation and should be treated as such.

>  The reason I like the one-sided confidence intervals for t-tests that we provide is that they make the tested hypothesis unmistakably clear. 

This is true, but in the case of one-sided t tests it is clear which information is irrelevant (= the infty).

>  Why do you feel so strongly about the one-sided CI here but not for the t-tests? Isn't this pretty inconsistent?

Because in the case of variance-explained estimates, it is not obvious which boundary is not "empirically determined", but set to be consistent with the hypothesis tested (e.g., if a CI contains [0, 1]). But to be clear, I would also prefer a two-sided CI for *t* tests.

> Personally, I think a much stronger argument for a 90% CI would be to use it for equivalence testing---if it is possible to declare a region of pratical equivalence.

Probably doesn't make any sense to provide defaults here.
