### ISSUE TITLE
apatable not knitting to word

### ISSUE THREAD

**Issue by kalifvaughn** [crsh/papaja#529]
Hello there,

This is odd, as this was just working the other day, but now I cannot get my table to show up when knitting to Word. It does not matter if I reference the table in the text, or if I just call the table in an unnamed R chunk. It just does not appear. 

It DOES appear if I knit to PDF, and it also appears if I use a default papaja template. But I am using the APA7 yaml header "hack" right now, and this is when it will not appear in Word.

Any thoughts or things I can try?

Thanks as always!

**Comment by conig** [comment]
Hard to say what might be happening without some code to look at. But you might be including something in the table which requires LaTeX for it to render.

Can you give us some code that will reproduce the problem? For example could you create a near identical table with the same columns and headers using mtcars which will cause the problem in a brand new apa6_docx rmd?

**Comment by kalifvaughn** [comment]
Hi conig,

The issue is most certainly related to LaTeX. It is a big stats table full of t-test, ANOVA, and regression results.

Are all LaTeX tables not cooperating with Word right now? It worked for awhile but then stopped. I eventually just edited the prior version manually.

**Comment by conig** [comment]
The issue is that papaja::apa_table does not translate latex syntax to word elements. Pandoc does that and not everything can be translated (latex is huge and growing).

Without seeing your code, something you added to the table cannot be translated to docx by pandoc and so is preventing the table from being rendered.

You could try removing each latex element one at a time until you find the culprit. Let us know what you discover.

**Comment by crsh** [comment]
Thanks for chiming in, James. Indeed, there is not much I can do to help without a minimal reproducible example.
