### ISSUE TITLE
Figure referencing in text

### ISSUE THREAD

**Issue by vasishth** [crsh/papaja#55]
Could you add an example of how figure referencing is done? I want to be able to refer to figures in text as "See Figure~\ref{fig:cars}" or whatever the analogous command is in Markdown.

**Comment by vasishth** [comment]
Actually, it's just a matter of adding an example like this: 

```{r cars, echo=FALSE, fig.cap="Here you see some interesting stuff about cars and such.\\label{figfoobar}"}
plot(cars)
```

What you always wanted to know about cars is shown in figure \ref{figfoobar}.

It took me hours to find this out!

**Comment by crsh** [comment]
Hi @vasishth,

thanks for the suggestions. As you have discovered you can use LaTeX code throughout your RMarkdown document and it will be parsed as expected if your target document is in PDF format. So you could also use `\autoref{fig:cars}` or most other variants.

I suspect that the trouble you had finding this solution is in part due to the fact that the markdown syntax used by pandoc to convert the document to LaTeX, Word, or HTML currently does not support these kinds of references to figures or tables. There has been [extensive discussion](https://github.com/jgm/pandoc/issues/813) on this issue including suggestions of possible syntaxes to implement such referencing.

Because I hope to be able to make papaja go to PDF and Word documents I had not yet added a LaTeX-dependent example to the document, but you are right that this option should be mentioned somewhere in the example file.

**Comment by crsh** [comment]
I have added this to the example file.
