### ISSUE TITLE
figure caption missing as well as figure not counted when using knitr::include_graphics

### ISSUE THREAD

**Issue by HenrikEckermann** [crsh/papaja#558]
Hi,

I noticed that the resulting word document of my papaja Rmd only counts R generated figures but the first figure has been included using `knitr::include_graphics("path_to_png")`.

Is this maybe a known issue or am I doing something wrong? I tried using text references instead of `fig.caption = "figure caption text"`.

Thanks for helping out!
Henrik

This is from my script leaving out the "`" in order to show the header:

(ref:flowchart-caption) Here is the caption.

{r, flowchart, fig.caption = "(ref:flow_chart-caption)"}
knitr::include_graphics(here::here("fig/flow_diagram_cropped.png"))

**Comment by crsh** [comment]
Hi Henrik,

it's been a long while, so I'm not sure if this issue is still relevant to you. But just in case:

The problem here is that a figure caption and number are only added if the chunk option `fig.cap` (*not* `fig.caption`) is non-NULL. You are seen this behavior because you are using an incorrectly named chunk option.
