### ISSUE TITLE
Affiliations list in Word

### ISSUE THREAD

**Issue by mvuorre** [crsh/papaja#59]
There's a problem with how the author affiliations are displayed when compiling the template to Word (2011, OS X El Capitan). Here's a screenshot:
<img width="441" alt="screen shot 2016-02-02 at 11 13 56" src="https://cloud.githubusercontent.com/assets/7349270/12755601/18a208f2-c99e-11e5-910b-d3bbc8abf32c.png">

It looks like that both in Word 2011 and LibreOffice. Compiling to PDF works fine.

```r
> sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.3 (El Capitan)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] rsconnect_0.4.1.11 htmltools_0.3      tools_3.2.2        yaml_2.1.13        rmarkdown_0.9.2   
[6] papaja_0.1.0.9054  digest_0.6.9     
```
pandoc 1.16.0.2

**Comment by crsh** [comment]
Hi Matti, thanks for reporting this. It appears that papaja will need a few updates before it works seemlessly with pandoc 1.16. I need to take a closer look at this to make sure I don't break compatibility with pandoc 1.14 (which is still the RStudio default).

**Comment by crsh** [comment]
Hi Matti, most of the bugs should be fixed in the latest development version (devtools::install_github("crsh/papaja", ref = "devel")). There is still a redundant abstract generated by pandoc; I'm not sure, yet, how to get rid of it. I'll take a closer look at this some other time.

The Word-support of pandoc is pretty basic; I'm considering switching to ODT because DOCX is pretty hacky and a lot of work. Moreover, Word should be able to open ODT, too. I'll have to do some experimenting.

**Comment by mvuorre** [comment]
Sweet, I just tried it and it works great (apart from the redundant abstract as you mention.)\

Thanks!
