### ISSUE TITLE
How to include full hyperlink text (e.g., "Table 1" instead of just "1") for tables in PDF documents?

### ISSUE THREAD

**Issue by perlatex** [crsh/papaja#597]
I'm facing an issue when generating PDF documents from `papaja::apa6_pdf()`. When referencing tables, the default hyperlink text shows only the number (e.g., "1"), but I would like it to display the full reference text, such as "Table 1" instead.

````r
---
title: "title"
documentclass     : "apa6" 
classoption       : "doc"    
link-citations    : yes
linkcolor         : red
urlcolor          : blue
citecolor         : blue
output            : 
  papaja::apa6_pdf:
    latex_engine: xelatex

header-includes   :
  - \usepackage{tabularray}
  - \usepackage{hyperref}
---


# chapter

The summary information see Table \@ref(tab:tableref), Some description.

```{r tableref}
library(tidyverse)
library(papaja)
iris %>% 
  head() %>% 
  apa_table(
    placement = "h",
    caption = "A summary table of the dataset."
  )
   
```
````

![ask](https://github.com/user-attachments/assets/70fe0744-f6bf-45af-ad0a-757bf99491f4)

This generates a hyperlink, but I want it to show "Table 1" rather than just "1". Is there a way to modify the hyperlink text to include the word "Table" instead of just the number?

Thanks in advance!

**Comment by crsh** [comment]
Hi there, thanks for reaching out. This question technically relates to the **bookdown** package rather than **papaja**. What you are looking for is something akin to `\autoref{}` in LaTeX, right? If you are being limited to PDF-output, you can just use the LaTeX command. I don't think there currently is output-format-agnostic analog in **bookdown** or pandoc. There is an open [feature request](https://github.com/jgm/pandoc/issues/7463) with pandoc to add this feature. An upvote over there could help.
