### ISSUE TITLE
References should be on new page

### ISSUE THREAD

**Issue by mattsigal** [crsh/papaja#60]
In APA Style, references should be listed on a new page. At present, this can be done by including $\pagebreak$ before `# References` in-text, but this leads to another issue: while the References appear on their own page, the content on the last page is now vertically distributed (see screenshot). ![screen shot 2016-03-30 at 10 29 50](https://cloud.githubusercontent.com/assets/1421758/14145577/644efe0e-f662-11e5-8e64-09bb9f81141c.png)

It would be great if `papaja` could set this break (default to TRUE when outputting to PDF).

**Comment by crsh** [comment]
Hi Matthew,

thanks for the report. First, if you want to insert a page break (this currently only works for PDF) all you need is `\pagebreak` (no `$` required). The resulting vertical spacing between paragraphs is a LaTeX default that is not suited well to your test example. If you want to prevent LaTeX from automatically adjusting vertical spacing between paragraphs you can simply add `\raggedbottom` to the beginning of your document. Moreover, using `\clearpage` or `\newpage` instead of `\pagebreak` will have the same effect (see this [SO question](http://tex.stackexchange.com/questions/736/pagebreak-vs-newpage)).

> It would be great if papaja could set this break (default to TRUE when outputting to PDF).

I'm not quite sure what you mean by this. Is there an RMarkdown-option to insert a page break before the reference section that I'm unaware of?

Thanks to this issue, I found a [Haskell filter](https://groups.google.com/forum/#!topic/pandoc-discuss/FzLrhk0vVbU) to enable page breaks for MS Word documents. I'll leave this issue open to remind me to play around with it.

**Comment by mattsigal** [comment]
You are correct!  I should have been using `\clearpage`.  That works great.

Adding the page break automatically isn't that necessary. Just thought it would be a convenience.

**Comment by crsh** [comment]
I'm closing this issue because I don't think it's feasible to add a filter to insert pagebreaks. I would rather wait until `pandoc` adds support for this.
