### ISSUE TITLE
"%" in apa_table() causes error

### ISSUE THREAD

**Issue by m-Py** [crsh/papaja#66]
Hello,

I am having troubles inserting a "%" sign into my tables using apa_table(). Using it in a string either in a table cell or as a column or row name causes an error when converting to .pdf (I know this error must be caused by the "%" sign; if I write "percent" instead, the conversion works).

Using "%%" or "%" I get: 

! Misplaced \noalign.
\bottomrule ->\noalign 
                       {\ifnum 0=`}\fi \@aboverulesep =\aboverulesep \global...
l.529 \bottomrule

pandoc: Error producing PDF from TeX source
Fehler: pandoc document conversion failed with error 43

Using "\%" I get:

Fehler: '\%' ist eine unbekannte Escape-Sequenz in der Zeichenkette beginnend mit ""\%"

Is this a Latex thing? I am not very familiar with Latex, so I cannot tell. Did this problem ever occur to anyone? I would like to give a sample description of several studies in one table, so a percent sign would be very convenient, for example to indicate the percent of German native speakers.

Best regards and thanks in advance!

Martin

**Comment by crsh** [comment]
Hi Martin,

this is, at the moment, a little tricky to understand. The first error message is generated by LaTeX because inserting `%` into a table will cause the rest of the line in the .tex-file to be comments and vital parts of the table markup will be ignored by the interpreter. So your hunch to escape it was correct.

The second error occurs because this time R doesn't know what `\%` is supposed to mean. R has it's own notation using `\`, e.g. newlines `\n` or tabs `\t`. So if it encounters anything starting with `\` R tries to interpret it. To avoid this you have to escape the escape symbol :laughing:: `\\%` should do the trick.

I am myself a little unhappy with this because it requires the user to know both systems. I want to add a safety net here (automatic escaping of `%`), but I think it will be a little while before I get around to it. Thanks for reporting this, though. I'll keep the issue open as a reminder.

Best regards,
Frederik

**Comment by m-Py** [comment]
Hi Frederik,

okay, I understand that. Using "\\%" is a funny hack - and it works - I did not get that idea by myself ;-)

Best regards, 
Martin
