### ISSUE TITLE
add \label{} to apa_table()

### ISSUE THREAD

**Issue by wanjam** [crsh/papaja#84]
Hi Frederik,

As I like to auto-reference tables and figures in text, I'd like to suggest adding an additional argument to apa_table(), to pass a \label{} to latex.
As a workaround, I use:
`apa_table(xyz$table,
          caption = 'caption text here}\\label{tab:figurelabel')`

I imagine something like this:
`apa_table(xyz$table,
          caption = 'caption text here', label ='tab:figurelabel')`

As far as I can see, that would just require a few additional lines in apa_table() and apa_table.latex().

Best,
Wanja

**Comment by crsh** [comment]
Thanks for the comment! I have not added this parameter  because I hope, I'll soon be able to automate the generation of labels through the use of the `bookdown` package. If this should, contrary to expectations, not work, I'll come back to your suggestion (I'll leave the issue open in the meantime).

As an aside, you can simply add the label inside the caption without having to fiddle with the braces (`caption = 'caption text here \\label{tab:figurelabel}'`).

**Comment by crsh** [comment]
As of 36b13a9e9cb5422aa17f12175d5494006ae55366 (install from development branch `devtools::install_github("crsh/papaja", ref = "devel")`), `papaja` uses `pdf_document2()` and `word_document2()` from the `bookdown` package. This enables the use of `bookdown` cross-referencing syntax including automatically generated table and figure labels as detailed [here](https://bookdown.org/yihui/bookdown/cross-references.html). Let me know if you encounter any problems.
