### ISSUE TITLE
Error in apa_table with lm object

### ISSUE THREAD

**Issue by m-Py** [crsh/papaja#87]
Hi Frederik,

when I create an `apa_table` from a lm object, this only works if I used the `data` argument to indicate the data.frame that the `lm` function should work on. If I use the `$` notation to access the vector within the data.frame, the pdf is not generated and the following error is thrown:

```
! Package caption Error: \caption outside float.

See the caption package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.156 ...ckslash{}begin\{threeparttable\} \caption

pandoc: Error producing PDF
Fehler: pandoc document conversion failed with error 43
```

[Here](https://gist.github.com/m-Py/bb3840d949dfef513ab4f2daa49551cd) is a reproducible example of this failure. 

Aside from this, I would also be interested to use apa_tables when I do not use apa6_pdf as output format; you mentioned that I can use apa6 style in R Markdown (and -- I hope -- apa_table) in other output format than apa6_pdf? When I use output: pdf_document I cannot render a document, which uses an apa_table; changing the `documentclass` to apa6_pdf also did not work.

Best regards,  
Martin

**Comment by crsh** [comment]
Hi Martin,

thanks for this bug report. I think I know what the problem is and it should be easy to fix. I'll get on it right away.

As for using `apa_table()` with other formats: It's is possible. For `apa_table()` to do what it does and work in the `apa6` document class I have to include a couple of extra LaTeX packages and other hackery. If you add [these lines](https://github.com/crsh/papaja/blob/master/inst/rmarkdown/templates/apa6/resources/apa6.tex#L66-L105) to the preamble of your TeX-file (e.g. as header include) it should work. If you don't use the the LaTeX `endfloat` package you need to omit lines 84-89, if you do use it, you only need to omit the `ifthenelse` bits.

**Comment by crsh** [comment]
Try installing the unstable version of `papaja` (`devtools::install_github("crsh/papaja", ref = "devel")`) and let me know if you encounter any other problems.

**Comment by m-Py** [comment]
Yes, it works now!
