### ISSUE TITLE
knitting prints latex table as commented r-code

### ISSUE THREAD

**Issue by RMHogervorst** [crsh/papaja#93]
I used the example from 
?apa_table
```
my_table <- apply(cars, 2, function(x) # Create data
   round(c(Mean = mean(x), SD = sd(x), Min = min(x), Max = max(x)), 2)
)

apa_table(
   my_table
   , align = c("l", "r", "r")
   , caption = "A summary table of the cars dataset."
   , note = "This table was created using apa\\_table()"
   , added_stub_head = "Descriptives"
)
```
However, this printed the latex with # before it. marking this as commented code.

## solution
when I set these options the latex is printed parsed correctly
`knitr::opts_chunk$set(echo = FALSE, results = "asis")`

**Comment by crsh** [comment]
Thanks for sharing. This is the intended behavior. You can also set the option `results = "asis"` for each chunk individually. I have added a remark in the details section of the `apa_table()`-documentation to clarify this.

**Comment by RMHogervorst** [comment]
Oh really? Thanks for the clarification. Why is this the default?

**Comment by crsh** [comment]
`papaja` uses the `knitr`-default `results = "markup"`. The reasons for sticking with this default are

1. it is the common default and what users expect
2. when printing the results of `apa_print()` from a chunk that uses `results =  "asis"` can break the document rendering because of the `$` (see #77).

**Comment by RMHogervorst** [comment]
Alright that makes sense. Thanks !
